# Generated by Django 4.2.17 on 2024-12-16 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Task_Management_System", "0005_alter_task_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="end_date",
            field=models.DateTimeField(),
        ),
    ]
