# Generated by Django 4.2.17 on 2024-12-19 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Task_Management_System", "0007_subtask"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subtask",
            old_name="task",
            new_name="parent_task",
        ),
    ]
